# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import sdk_pb2 as sdk__pb2

GRPC_GENERATED_VERSION = "1.74.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in sdk_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ParameterStub(object):
    def __init__(self, channel):
        self.GetInputJSONString = channel.unary_unary(
            "/cafesdk.Parameter/GetInputJSONString",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=sdk__pb2.InputJSONStringResponse.FromString,
            _registered_method=True,
        )


class ParameterServicer(object):
    def GetInputJSONString(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ParameterServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetInputJSONString": grpc.unary_unary_rpc_method_handler(
            servicer.GetInputJSONString,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=sdk__pb2.InputJSONStringResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("cafesdk.Parameter", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("cafesdk.Parameter", rpc_method_handlers)


class Parameter(object):
    @staticmethod
    def GetInputJSONString(
        request, target, options=(), channel_credentials=None, call_credentials=None,
        insecure=False, compression=None, wait_for_ready=None, timeout=None, metadata=None
    ):
        return grpc.experimental.unary_unary(
            request, target, "/cafesdk.Parameter/GetInputJSONString",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            sdk__pb2.InputJSONStringResponse.FromString,
            options, channel_credentials, insecure, call_credentials, compression,
            wait_for_ready, timeout, metadata, _registered_method=True
        )


class ResultStub(object):
    def __init__(self, channel):
        self.SetTableHeader = channel.unary_unary(
            "/cafesdk.Result/SetTableHeader",
            request_serializer=sdk__pb2.TableHeader.SerializeToString,
            response_deserializer=sdk__pb2.Response.FromString,
            _registered_method=True,
        )
        self.PushData = channel.unary_unary(
            "/cafesdk.Result/PushData",
            request_serializer=sdk__pb2.Data.SerializeToString,
            response_deserializer=sdk__pb2.Response.FromString,
            _registered_method=True,
        )


class ResultServicer(object):
    def SetTableHeader(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PushData(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ResultServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SetTableHeader": grpc.unary_unary_rpc_method_handler(
            servicer.SetTableHeader,
            request_deserializer=sdk__pb2.TableHeader.FromString,
            response_serializer=sdk__pb2.Response.SerializeToString,
        ),
        "PushData": grpc.unary_unary_rpc_method_handler(
            servicer.PushData,
            request_deserializer=sdk__pb2.Data.FromString,
            response_serializer=sdk__pb2.Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("cafesdk.Result", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("cafesdk.Result", rpc_method_handlers)


class Result(object):
    @staticmethod
    def SetTableHeader(
        request, target, options=(), channel_credentials=None, call_credentials=None,
        insecure=False, compression=None, wait_for_ready=None, timeout=None, metadata=None
    ):
        return grpc.experimental.unary_unary(
            request, target, "/cafesdk.Result/SetTableHeader",
            sdk__pb2.TableHeader.SerializeToString,
            sdk__pb2.Response.FromString,
            options, channel_credentials, insecure, call_credentials, compression,
            wait_for_ready, timeout, metadata, _registered_method=True
        )

    @staticmethod
    def PushData(
        request, target, options=(), channel_credentials=None, call_credentials=None,
        insecure=False, compression=None, wait_for_ready=None, timeout=None, metadata=None
    ):
        return grpc.experimental.unary_unary(
            request, target, "/cafesdk.Result/PushData",
            sdk__pb2.Data.SerializeToString,
            sdk__pb2.Response.FromString,
            options, channel_credentials, insecure, call_credentials, compression,
            wait_for_ready, timeout, metadata, _registered_method=True
        )


class LogStub(object):
    def __init__(self, channel):
        self.Debug = channel.unary_unary(
            "/cafesdk.Log/Debug",
            request_serializer=sdk__pb2.LogBody.SerializeToString,
            response_deserializer=sdk__pb2.Response.FromString,
            _registered_method=True,
        )
        self.Info = channel.unary_unary(
            "/cafesdk.Log/Info",
            request_serializer=sdk__pb2.LogBody.SerializeToString,
            response_deserializer=sdk__pb2.Response.FromString,
            _registered_method=True,
        )
        self.Warn = channel.unary_unary(
            "/cafesdk.Log/Warn",
            request_serializer=sdk__pb2.LogBody.SerializeToString,
            response_deserializer=sdk__pb2.Response.FromString,
            _registered_method=True,
        )
        self.Error = channel.unary_unary(
            "/cafesdk.Log/Error",
            request_serializer=sdk__pb2.LogBody.SerializeToString,
            response_deserializer=sdk__pb2.Response.FromString,
            _registered_method=True,
        )


class LogServicer(object):
    def Debug(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Info(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Warn(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Error(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_LogServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Debug": grpc.unary_unary_rpc_method_handler(
            servicer.Debug,
            request_deserializer=sdk__pb2.LogBody.FromString,
            response_serializer=sdk__pb2.Response.SerializeToString,
        ),
        "Info": grpc.unary_unary_rpc_method_handler(
            servicer.Info,
            request_deserializer=sdk__pb2.LogBody.FromString,
            response_serializer=sdk__pb2.Response.SerializeToString,
        ),
        "Warn": grpc.unary_unary_rpc_method_handler(
            servicer.Warn,
            request_deserializer=sdk__pb2.LogBody.FromString,
            response_serializer=sdk__pb2.Response.SerializeToString,
        ),
        "Error": grpc.unary_unary_rpc_method_handler(
            servicer.Error,
            request_deserializer=sdk__pb2.LogBody.FromString,
            response_serializer=sdk__pb2.Response.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("cafesdk.Log", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("cafesdk.Log", rpc_method_handlers)


class Log(object):
    @staticmethod
    def Debug(
        request, target, options=(), channel_credentials=None, call_credentials=None,
        insecure=False, compression=None, wait_for_ready=None, timeout=None, metadata=None
    ):
        return grpc.experimental.unary_unary(
            request, target, "/cafesdk.Log/Debug",
            sdk__pb2.LogBody.SerializeToString,
            sdk__pb2.Response.FromString,
            options, channel_credentials, insecure, call_credentials, compression,
            wait_for_ready, timeout, metadata, _registered_method=True
        )

    @staticmethod
    def Info(
        request, target, options=(), channel_credentials=None, call_credentials=None,
        insecure=False, compression=None, wait_for_ready=None, timeout=None, metadata=None
    ):
        return grpc.experimental.unary_unary(
            request, target, "/cafesdk.Log/Info",
            sdk__pb2.LogBody.SerializeToString,
            sdk__pb2.Response.FromString,
            options, channel_credentials, insecure, call_credentials, compression,
            wait_for_ready, timeout, metadata, _registered_method=True
        )

    @staticmethod
    def Warn(
        request, target, options=(), channel_credentials=None, call_credentials=None,
        insecure=False, compression=None, wait_for_ready=None, timeout=None, metadata=None
    ):
        return grpc.experimental.unary_unary(
            request, target, "/cafesdk.Log/Warn",
            sdk__pb2.LogBody.SerializeToString,
            sdk__pb2.Response.FromString,
            options, channel_credentials, insecure, call_credentials, compression,
            wait_for_ready, timeout, metadata, _registered_method=True
        )

    @staticmethod
    def Error(
        request, target, options=(), channel_credentials=None, call_credentials=None,
        insecure=False, compression=None, wait_for_ready=None, timeout=None, metadata=None
    ):
        return grpc.experimental.unary_unary(
            request, target, "/cafesdk.Log/Error",
            sdk__pb2.LogBody.SerializeToString,
            sdk__pb2.Response.FromString,
            options, channel_credentials, insecure, call_credentials, compression,
            wait_for_ready, timeout, metadata, _registered_method=True
        )
