# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sdk.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    "",
    "sdk.proto",
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsdk.proto\x12\x07\x63\x61\x66\x65sdk\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/descriptor.proto\";\n\x17InputJSONStringResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x12\n\njsonString\x18\x02 \x01(\t\"8\n\x0bTableHeader\x12)\n\x07headers\x18\x01 \x03(\x0b\x32\x18.cafesdk.TableHeaderItem\"=\n\x0fTableHeaderItem\x12\r\n\x05label\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x0e\n\x06\x66ormat\x18\x03 \x01(\t\"\x1a\n\x04\x44\x61ta\x12\x12\n\njsonString\x18\x01 \x01(\t\"\x16\n\x07LogBody\x12\x0b\n\x03log\x18\x01 \x01(\t\")\n\x08Response\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2]\n\tParameter\x12P\n\x12GetInputJSONString\x12\x16.google.protobuf.Empty\x1a .cafesdk.InputJSONStringResponse\"\x002u\n\x06Result\x12;\n\x0eSetTableHeader\x12\x14.cafesdk.TableHeader\x1a\x11.cafesdk.Response\"\x00\x12.\n\x08PushData\x12\r.cafesdk.Data\x1a\x11.cafesdk.Response\"\x002\xc3\x01\n\x03Log\x12.\n\x05\x44\x65\x62ug\x12\x10.cafesdk.LogBody\x1a\x11.cafesdk.Response\"\x00\x12-\n\x04Info\x12\x10.cafesdk.LogBody\x1a\x11.cafesdk.Response\"\x00\x12-\n\x04Warn\x12\x10.cafesdk.LogBody\x1a\x11.cafesdk.Response\"\x00\x12.\n\x05\x45rror\x12\x10.cafesdk.LogBody\x1a\x11.cafesdk.Response\"\x00:7\n\x0e\x61llowed_values\x12\x1d.google.protobuf.FieldOptions\x18\xd0\x86\x03 \x01(\tB\x0cZ\n./;cafesdkb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "sdk_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\n./;cafesdk"
    _globals["_INPUTJSONSTRINGRESPONSE"]._serialized_start = 85
    _globals["_INPUTJSONSTRINGRESPONSE"]._serialized_end = 144
    _globals["_TABLEHEADER"]._serialized_start = 146
    _globals["_TABLEHEADER"]._serialized_end = 202
    _globals["_TABLEHEADERITEM"]._serialized_start = 204
    _globals["_TABLEHEADERITEM"]._serialized_end = 265
    _globals["_DATA"]._serialized_start = 267
    _globals["_DATA"]._serialized_end = 293
    _globals["_LOGBODY"]._serialized_start = 295
    _globals["_LOGBODY"]._serialized_end = 317
    _globals["_RESPONSE"]._serialized_start = 319
    _globals["_RESPONSE"]._serialized_end = 360
    _globals["_PARAMETER"]._serialized_start = 362
    _globals["_PARAMETER"]._serialized_end = 455
    _globals["_RESULT"]._serialized_start = 457
    _globals["_RESULT"]._serialized_end = 574
    _globals["_LOG"]._serialized_start = 577
    _globals["_LOG"]._serialized_end = 772
# @@protoc_insertion_point(module_scope)
